version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "vitest",
    "nodejs"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"